/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.help-infor[_ngcontent-%COMP%]{\r\n    padding: .1rem .24rem;\r\n}\r\n.help-infor[_ngcontent-%COMP%]   .title-lists[_ngcontent-%COMP%]{\r\n    color: #333;\r\n    font-size: .28rem;\r\n    line-height: 2.2;\r\n}\r\n.help-infor[_ngcontent-%COMP%]   .sub-title-lists[_ngcontent-%COMP%]{\r\n    color: #444;\r\n    font-size: .26rem;\r\n}\r\n.help-infor[_ngcontent-%COMP%]   p[_ngcontent-%COMP%]{\r\n    font-size: .26rem;\r\n    color: #666;\r\n    line-height: 1.8;\r\n}\r\n.help-infor[_ngcontent-%COMP%]   .help-img[_ngcontent-%COMP%]{\r\n    padding-top: .16rem;\r\n    text-align: center;\r\n}'];
//# sourceMappingURL=help-detail.component.css.shim.ngstyle.js.map